### ISSUE TITLE
Error while rendering: com/xuggle/mediatool/ToolFactory

### ISSUE THREAD

**Issue by Steffens1950** [zdila/gpx-animator#127]
With the new version 1.4 snapshot I was not able to render the file. Attached you will find the gpx file, the xlm and the screenshot.
Can you please investigate what can be my mistake.

Best reagrds
Peter
[Print_Dienstag, 10. Dezember 2019_14h41m13s_001_.pdf](https://github.com/zdila/gpx-animator/files/3945143/Print_Dienstag.10.Dezember.2019_14h41m13s_001_.pdf)

[2019-08_15 klein.zip](https://github.com/zdila/gpx-animator/files/3945155/2019-08_15.klein.zip)
[Test 2019-12-10.ga.xml.zip](https://github.com/zdila/gpx-animator/files/3945158/Test.2019-12-10.ga.xml.zip)

**Comment by McPringle** [comment]
Thank you very much for your good report including the files. Today in the evening I’ll attend the Hackergarten in Berne and I’m going to suggest GPX Animator as the topic. Hopefully we’ll have a small group to work on the issues.

**Comment by McPringle** [comment]
I tested it on my Linux machine and the video got rendered without any issues. What operating system are you using? Can you please provide the output of `java -version`?

**Comment by Steffens1950** [comment]
Java Version 8 Update 231 (Build 1.8.0_231-b11)

Windows 10 Home Version 1903 Betriebssystembuild 18362.476

 

Von: Marcus Fihlon <notifications@github.com> 
Gesendet: Dienstag, 10. Dezember 2019 21:08
An: zdila/gpx-animator <gpx-animator@noreply.github.com>
Cc: Steffens1950 <pst1950@t-online.de>; Author <author@noreply.github.com>
Betreff: Re: [zdila/gpx-animator] Error while rendering: com/xuggle/mediatool/ToolFactory (#127)

 

I tested it on my Linux machine and the video got rendered without any issues. What operating system are you using? Can you please provide the output of java -version?

**Comment by McPringle** [comment]
I installed Windows 10 Home 64 Bit Version 10.0.18363 Build 18363 in a Virtual Box VM including Java 1.8.0_232 64 Bit build 1.8.0_231-b11. GPX Animator worked fine and created the video file based on your files provided.

How do you start GPX Animator? By a double click or by using the command line: `java -jar GpxAnimator-1.4-SNAPSHOT.jar`

**Comment by Steffens1950** [comment]
I start it with a double click.

Can you please explain the other way. On which place I have to write the command line?

 

Tomorrow I will try it without the virus program.

 

Von: Marcus Fihlon <notifications@github.com> 
Gesendet: Mittwoch, 11. Dezember 2019 15:02
An: zdila/gpx-animator <gpx-animator@noreply.github.com>
Cc: Steffens1950 <pst1950@t-online.de>; Author <author@noreply.github.com>
Betreff: Re: [zdila/gpx-animator] Error while rendering: com/xuggle/mediatool/ToolFactory (#127)

 

I installed Windows 10 Home 64 Bit Version 10.0.18363 Build 18363 in a Virtual Box VM including Java 1.8.0_232 64 Bit build 1.8.0_231-b11. GPX Animator worked fine and created the video file based on your files provided.

How do you start GPX Animator? By a double click or by using the command line: java -jar GpxAnimator-1.4-SNAPSHOT.jar

**Comment by McPringle** [comment]
Let's try it:

1. Click on the Windows icon on the bottom left edge of the screen (Start icon)
2. Type `PowerShell` and click on the search result `Windows PowerShell` to start it
3. Type `cd Downloads` and press `Enter` (in case `Downloads` is the directory you downloaded GPX Animator to)
4. Type `java -version` and copy all the output to a new comment here
5. Type `java -jar GpxAnimator-1.4-SNAPSHOT.jar` and press `Enter`

Now, try to render your animation. If an error occurs, you will see some weird output in the PowerShell window. Please copy it to a new comment here, that's what I need to get further into this issue.

**Comment by Steffens1950** [comment]
Hi Marcus,

 

I have done it but without success.

It takes some milliseconds of work and then I c an see the same error information.

I have done it also without virusscanner. The same

 

 

Thanks for the guiding. I’m a typical user☹

 

Best regards

Peter

 

PS D:\daten\papkorb\GPX> java -version

java version "1.8.0_231"

Java(TM) SE Runtime Environment (build 1.8.0_231-b11)

Java HotSpot(TM) Client VM (build 25.231-b11, mixed mode, sharing)

 

 

 

Windows PowerShell

Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

 

Lernen Sie das neue plattformübergreifende PowerShell kennen – https://aka.ms/pscore6

 

PS C:\Users\pst19> cd d:

PS D:\> cd daten

PS D:\daten> cd papkorb

PS D:\daten\papkorb> cd gpx

PS D:\daten\papkorb\gpx> cd maion

cd : Der Pfad "D:\daten\papkorb\gpx\maion" kann nicht gefunden werden, da er nicht vorhanden ist.

In Zeile:1 Zeichen:1

+ cd maion

+ ~~~~~~~~

    + CategoryInfo          : ObjectNotFound: (D:\daten\papkorb\gpx\maion:String) [Set-Location], ItemNotFoundExceptio

   n

    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

 

PS D:\daten\papkorb\gpx> cd main

PS D:\daten\papkorb\gpx\main> java -jar GpxAnimator-1.4-SNAPSHOT.jar

java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/xuggle/mediatool/ToolFactory

        at java.util.concurrent.FutureTask.report(Unknown Source)

        at java.util.concurrent.FutureTask.get(Unknown Source)

        at javax.swing.SwingWorker.get(Unknown Source)

        at sk.freemap.gpxAnimator.ui.MainFrame$14$1.done(MainFrame.java:483)

        at javax.swing.SwingWorker$5.run(Unknown Source)

        at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)

        at sun.swing.AccumulativeRunnable.run(Unknown Source)

        at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)

        at javax.swing.Timer.fireActionPerformed(Unknown Source)

        at javax.swing.Timer$DoPostEvent.run(Unknown Source)

        at java.awt.event.InvocationEvent.dispatch(Unknown Source)

        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)

        at java.awt.EventQueue.access$500(Unknown Source)

        at java.awt.EventQueue$3.run(Unknown Source)

        at java.awt.EventQueue$3.run(Unknown Source)

        at java.security.AccessController.doPrivileged(Native Method)

        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)

        at java.awt.EventQueue.dispatchEvent(Unknown Source)

        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)

        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)

        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)

        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)

        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)

        at java.awt.EventDispatchThread.run(Unknown Source)

Caused by: java.lang.NoClassDefFoundError: com/xuggle/mediatool/ToolFactory

        at sk.freemap.gpxAnimator.frameWriter.VideoFrameWriter.<init>(VideoFrameWriter.java:31)

        at sk.freemap.gpxAnimator.Renderer.render(Renderer.java:195)

        at sk.freemap.gpxAnimator.ui.MainFrame$14$1.doInBackground(MainFrame.java:452)

        at sk.freemap.gpxAnimator.ui.MainFrame$14$1.doInBackground(MainFrame.java:449)

        at javax.swing.SwingWorker$1.call(Unknown Source)

        at java.util.concurrent.FutureTask.run(Unknown Source)

        at javax.swing.SwingWorker.run(Unknown Source)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

        at java.lang.Thread.run(Unknown Source)

Caused by: java.lang.ClassNotFoundException: com.xuggle.mediatool.ToolFactory

        at java.net.URLClassLoader.findClass(Unknown Source)

        at java.lang.ClassLoader.loadClass(Unknown Source)

        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)

        at java.lang.ClassLoader.loadClass(Unknown Source)

        ... 10 more

 

 

Von: Marcus Fihlon <notifications@github.com> 
Gesendet: Donnerstag, 12. Dezember 2019 10:12
An: zdila/gpx-animator <gpx-animator@noreply.github.com>
Cc: Steffens1950 <pst1950@t-online.de>; Author <author@noreply.github.com>
Betreff: Re: [zdila/gpx-animator] Error while rendering: com/xuggle/mediatool/ToolFactory (#127)

 

Let's try it:

1.	Click on the Windows icon on the bottom left edge of the screen (Start icon)
2.	Type PowerShell and click on the search result Windows PowerShell to start it
3.	Type cd Downloads and press Enter (in case Downloads is the directory you downloaded GPX Animator to)
4.	Type java -version and copy all the output to a new comment here
5.	Type java -jar GpxAnimator-1.4-SNAPSHOT.jar and press Enter

Now, try to render your animation. If an error occurs, you will see some weird output in the PowerShell window. Please copy it to a new comment here, that's what I need to get further into this issue.

**Comment by McPringle** [comment]
Thank you very much for all the information, that helps a lot to understand your problem. Please download the file [GpxAnimator-1.4-SNAPSHOT.one-jar.jar](https://mcpringle.duckdns.org/nextcloud/s/CgLNJ74wGm4ANLW) from my storage device and run it the same way as the last time. **fingerscrossed**

**Comment by Steffens1950** [comment]
Hi Marcus,

 

I have done it, but without success. I have also tired it on another windows laptop, Also with success

 

 

Best regards

Peter

 

 

Windows PowerShell

Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

 

Lernen Sie das neue plattformübergreifende PowerShell kennen – https://aka.ms/pscore6

 

PS C:\Users\pst19> cd d:

PS D:\> cd daten

PS D:\daten> cd papkorb

PS D:\daten\papkorb> cd gpx2

PS D:\daten\papkorb\gpx2> cd main

PS D:\daten\papkorb\gpx2\main> java -jar gpxanimator-1.4-snapshot.jar

[  0%] computed zoom is 10

java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/xuggle/mediatool/ToolFactory

        at java.util.concurrent.FutureTask.report(Unknown Source)

        at java.util.concurrent.FutureTask.get(Unknown Source)

        at javax.swing.SwingWorker.get(Unknown Source)

        at sk.freemap.gpxAnimator.ui.MainFrame$14$1.done(MainFrame.java:449)

        at javax.swing.SwingWorker$5.run(Unknown Source)

        at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)

        at sun.swing.AccumulativeRunnable.run(Unknown Source)

        at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)

        at javax.swing.Timer.fireActionPerformed(Unknown Source)

        at javax.swing.Timer$DoPostEvent.run(Unknown Source)

        at java.awt.event.InvocationEvent.dispatch(Unknown Source)

        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)

        at java.awt.EventQueue.access$500(Unknown Source)

        at java.awt.EventQueue$3.run(Unknown Source)

        at java.awt.EventQueue$3.run(Unknown Source)

        at java.security.AccessController.doPrivileged(Native Method)

        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)

        at java.awt.EventQueue.dispatchEvent(Unknown Source)

        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)

        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)

        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)

        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)

        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)

        at java.awt.EventDispatchThread.run(Unknown Source)

Caused by: java.lang.NoClassDefFoundError: com/xuggle/mediatool/ToolFactory

        at sk.freemap.gpxAnimator.frameWriter.VideoFrameWriter.<init>(VideoFrameWriter.java:31)

        at sk.freemap.gpxAnimator.Renderer.render(Renderer.java:259)

        at sk.freemap.gpxAnimator.ui.MainFrame$14$1.doInBackground(MainFrame.java:418)

        at sk.freemap.gpxAnimator.ui.MainFrame$14$1.doInBackground(MainFrame.java:415)

        at javax.swing.SwingWorker$1.call(Unknown Source)

        at java.util.concurrent.FutureTask.run(Unknown Source)

        at javax.swing.SwingWorker.run(Unknown Source)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

        at java.lang.Thread.run(Unknown Source)

Caused by: java.lang.ClassNotFoundException: com.xuggle.mediatool.ToolFactory

        at java.net.URLClassLoader.findClass(Unknown Source)

        at java.lang.ClassLoader.loadClass(Unknown Source)

        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)

        at java.lang.ClassLoader.loadClass(Unknown Source)

        ... 10 more

 

Von: Marcus Fihlon <notifications@github.com> 
Gesendet: Donnerstag, 12. Dezember 2019 18:32
An: zdila/gpx-animator <gpx-animator@noreply.github.com>
Cc: Steffens1950 <pst1950@t-online.de>; Author <author@noreply.github.com>
Betreff: Re: [zdila/gpx-animator] Error while rendering: com/xuggle/mediatool/ToolFactory (#127)

 

Thank you very much for all the information, that helps a lot to understand your problem. Please download the file GpxAnimator-1.4-SNAPSHOT.one-jar.jar <https://mcpringle.duckdns.org/nextcloud/s/CgLNJ74wGm4ANLW>  from my storage device and run it the same way as the last time. fingerscrossed

**Comment by McPringle** [comment]
So nothing worked. This issue is getting complicated because I can't reproduce this error. Do you have other Java software running on your computer or is GPX Animator the only one? If it is the only one, please install exactly the same Java Runtime Environment I have chosen on my Windows 10 Home test system: https://mcpringle.duckdns.org/nextcloud/s/goi6672eYQtT9tB

After installation, please try it again at the command line.

For the next major version ([v2.0](https://github.com/zdila/gpx-animator/issues?q=is%3Aopen+is%3Aissue+milestone%3Av2.0)) we plan to make the installation much easier with #67 and #112.

**Comment by McPringle** [comment]
This is how your animation looks like when I render it with GPX Animator on my machine: https://mcpringle.duckdns.org/nextcloud/s/DnPR3sGpL8bDzHY

**Comment by Steffens1950** [comment]
Hi Marcus,

 

I cannot see, that there is any program using JAVA.

I have done it according your instructions, but the result is negative.

 

 

Windows PowerShell

Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

 

Lernen Sie das neue plattformübergreifende PowerShell kennen – https://aka.ms/pscore6

 

PS C:\Users\pst19> cd d:

PS D:\> cd daten

PS D:\daten> cd papkorb

PS D:\daten\papkorb> cd gpx2

PS D:\daten\papkorb\gpx2> cd main

PS D:\daten\papkorb\gpx2\main> java -jar GpxAnimator-1.4-SNAPSHOT.jar

[  0%] computed zoom is 10

java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/xuggle/mediatool/ToolFactory

        at java.util.concurrent.FutureTask.report(Unknown Source)

        at java.util.concurrent.FutureTask.get(Unknown Source)

        at javax.swing.SwingWorker.get(Unknown Source)

        at sk.freemap.gpxAnimator.ui.MainFrame$14$1.done(MainFrame.java:449)

        at javax.swing.SwingWorker$5.run(Unknown Source)

        at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)

        at sun.swing.AccumulativeRunnable.run(Unknown Source)

        at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)

        at javax.swing.Timer.fireActionPerformed(Unknown Source)

        at javax.swing.Timer$DoPostEvent.run(Unknown Source)

        at java.awt.event.InvocationEvent.dispatch(Unknown Source)

        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)

        at java.awt.EventQueue.access$500(Unknown Source)

        at java.awt.EventQueue$3.run(Unknown Source)

        at java.awt.EventQueue$3.run(Unknown Source)

        at java.security.AccessController.doPrivileged(Native Method)

        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)

        at java.awt.EventQueue.dispatchEvent(Unknown Source)

        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)

        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)

        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)

        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)

        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)

        at java.awt.EventDispatchThread.run(Unknown Source)

Caused by: java.lang.NoClassDefFoundError: com/xuggle/mediatool/ToolFactory

        at sk.freemap.gpxAnimator.frameWriter.VideoFrameWriter.<init>(VideoFrameWriter.java:31)

        at sk.freemap.gpxAnimator.Renderer.render(Renderer.java:259)

        at sk.freemap.gpxAnimator.ui.MainFrame$14$1.doInBackground(MainFrame.java:418)

        at sk.freemap.gpxAnimator.ui.MainFrame$14$1.doInBackground(MainFrame.java:415)

        at javax.swing.SwingWorker$1.call(Unknown Source)

        at java.util.concurrent.FutureTask.run(Unknown Source)

        at javax.swing.SwingWorker.run(Unknown Source)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

        at java.lang.Thread.run(Unknown Source)

Caused by: java.lang.ClassNotFoundException: com.xuggle.mediatool.ToolFactory

        at java.net.URLClassLoader.findClass(Unknown Source)

        at java.lang.ClassLoader.loadClass(Unknown Source)

        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)

        at java.lang.ClassLoader.loadClass(Unknown Source)

        ... 10 more

 

 

BR

Peter

 

Von: Marcus Fihlon <notifications@github.com> 
Gesendet: Samstag, 14. Dezember 2019 19:49
An: zdila/gpx-animator <gpx-animator@noreply.github.com>
Cc: Steffens1950 <pst1950@t-online.de>; Author <author@noreply.github.com>
Betreff: Re: [zdila/gpx-animator] Error while rendering: com/xuggle/mediatool/ToolFactory (#127)

 

So nothing worked. This issue is getting complicated because I can't reproduce this error. Do you have other Java software running on your computer or is GPX Animator the only one? If it is the only one, please install exactly the same Java Runtime Environment I have chosen on my Windows 10 Home test system: https://mcpringle.duckdns.org/nextcloud/s/goi6672eYQtT9tB

After installation, please try it again at the command line.

For the next major version (v2.0 <https://github.com/zdila/gpx-animator/issues?q=is%3Aopen+is%3Aissue+milestone%3Av2.0> ) we plan to make the installation much easier with #67 <https://github.com/zdila/gpx-animator/issues/67>  and #112 <https://github.com/zdila/gpx-animator/issues/112> .

**Comment by McPringle** [comment]
I tried different computers and notebooks but was not able to reproduce this error. I'll remove the tag for v1.4 and release the official v1.4 tomorrow. Bit I will continue to investigate this issue!

**Comment by McPringle** [comment]
Hi, @Steffens1950. A few minutes ago I released v1.4 of GPX Animator. Just for information. As I mentioned, I tried to reproduce your problem on several computers but failed. I could render your video on every machine, I have access to. Now I would try to use a newer version of Java on your machine to check if the problem is there. I'll provide you the latest stable Java version for your system and will post here a download link later today.

**Comment by Steffens1950** [comment]
Thanks

 

Von: Marcus Fihlon <notifications@github.com> 
Gesendet: Freitag, 20. Dezember 2019 09:45
An: zdila/gpx-animator <gpx-animator@noreply.github.com>
Cc: Steffens1950 <pst1950@t-online.de>; Mention <mention@noreply.github.com>
Betreff: Re: [zdila/gpx-animator] Error while rendering: com/xuggle/mediatool/ToolFactory (#127)

 

Hi, @Steffens1950 <https://github.com/Steffens1950> . A few minutes ago I released v1.4 of GPX Animator. Just for information. As I mentioned, I tried to reproduce your problem on several computers but failed. I could render your video on every machine, I have access to. Now I would try to use a newer version of Java on your machine to check if the problem is there. I'll provide you the latest stable Java version for your system and will post here a download link later today.

**Comment by McPringle** [comment]
Hi @Steffens1950 

I created a Windows installer for GPX Animator, which installs a bundle using an own Java and creates a start menu entry. Please check it out! You can download it here:

https://mcpringle.duckdns.org/nextcloud/s/E4snT9Qk3EHemPS

I guess you have a 64 Bit Windows version (as of today, most users have 64 Bit). So you need to download the following file:

    gpx-animator_windows-x64_1_4.exe

This is the first version of an installer. It is not signed, so Windows will complain of an insecure app. Please execute it anyway (there is a link in the warning dialog to di so). If it works on your machine, I will continue my work on the installer and try to sign it and make it secure in a "Microsoft way".

**Comment by Steffens1950** [comment]
Dear Marcus,

 

I t   w o r k s!!

 

The only problem was, that I have to chose a real output file (directory). 

The proposed directory is not working.



 

Have a wonderful Christmas Time

Peter

 

 

Von: Marcus Fihlon <notifications@github.com> 
Gesendet: Sonntag, 22. Dezember 2019 21:18
An: zdila/gpx-animator <gpx-animator@noreply.github.com>
Cc: Steffens1950 <pst1950@t-online.de>; Mention <mention@noreply.github.com>
Betreff: Re: [zdila/gpx-animator] Error while rendering: com/xuggle/mediatool/ToolFactory (#127)

 

Hi @Steffens1950 <https://github.com/Steffens1950> 

I created a Windows installer for GPX Animator, which installs a bundle using an own Java and creates a start menu entry. Please check it out! You can download it here:

https://mcpringle.duckdns.org/nextcloud/s/E4snT9Qk3EHemPS

I guess you have a 64 Bit Windows version (as of today, most users have 64 Bit). So you need to download the following file:

gpx-animator_windows-x64_1_4.exe

This is the first version of an installer. It is not signed, so Windows will complain of an insecure app. Please execute it anyway (there is a link in the warning dialog to di so). If it works on your machine, I will continue my work on the installer and try to sign it and make it secure in a "Microsoft way".

**Comment by McPringle** [comment]
Thank you very much for your reply and for testing so much to find a solution! I'll close this issue now and will work more on #139 to improve the installers and make them available to the public with the next release. The problem with the output directory might be a Windows-based permission problem because the default output directory is the program directory which might be protected on Windows systems. I'll fix this in the next version and created issue #141 for that.

Enjoy your Xmas time and a happy new year!
