### ISSUE TITLE
Errors when using OSM background maps

### ISSUE THREAD

**Issue by okievv** [zdila/gpx-animator#144]
I tried underlying OSM background maps when rendering a gpx file (which works fine without background map).
I encountered 2 different types of errors (see java stack below):
1. a "null" error when selecting OpenStreetMap (German Style), and
2. a "error when reading tile https://b.tile.openstreetmap.org/4/5/9.png" when using OpenStreetMap (Mapnik)

I left any other parameter on default. My internet connection is quite fine in Europe.
Regards, okievv

**Stack for 1):**
[  5%] Reading Map Tile: 1/20
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at javax.swing.SwingWorker.get(SwingWorker.java:602)
	at sk.freemap.gpxAnimator.ui.MainFrame$13$1.done(MainFrame.java:427)
	at javax.swing.SwingWorker$5.run(SwingWorker.java:737)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:832)
	at sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:842)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at org.GNOME.Accessibility.AtkWrapper$5.dispatchEvent(AtkWrapper.java:697)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
	at sk.freemap.gpxAnimator.Map.drawMap(Map.java:86)
	at sk.freemap.gpxAnimator.Renderer.render(Renderer.java:206)
	at sk.freemap.gpxAnimator.ui.MainFrame$13$1.doInBackground(MainFrame.java:396)
	at sk.freemap.gpxAnimator.ui.MainFrame$13$1.doInBackground(MainFrame.java:393)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.conerror reading tile https://b.tile.openstreetmap.org/4/5/9.pngcurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Stack for 2)**
[  5%] Reading Map Tile: 1/20
java.util.concurrent.ExecutionException: sk.freemap.gpxAnimator.UserException: error reading tile https://b.tile.openstreetmap.org/4/5/9.png
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at javax.swing.SwingWorker.get(SwingWorker.java:602)
	at sk.freemap.gpxAnimator.ui.MainFrame$13$1.done(MainFrame.java:427)
	at javax.swing.SwingWorker$5.run(SwingWorker.java:737)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:832)
	at sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:842)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at org.GNOME.Accessibility.AtkWrapper$5.dispatchEvent(AtkWrapper.java:697)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: sk.freemap.gpxAnimator.UserException: error reading tile https://b.tile.openstreetmap.org/4/5/9.png
	at sk.freemap.gpxAnimator.Map.drawMap(Map.java:82)
	at sk.freemap.gpxAnimator.Renderer.render(Renderer.java:206)
	at sk.freemap.gpxAnimator.ui.MainFrame$13$1.doInBackground(MainFrame.java:396)
	at sk.freemap.gpxAnimator.ui.MainFrame$13$1.doInBackground(MainFrame.java:393)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.imageio.IIOException: Can't get input stream from URL!
	at javax.imageio.ImageIO.read(ImageIO.java:1395)
	at sk.freemap.gpxAnimator.Map.drawMap(Map.java:80)
	... 9 more
Caused by: java.io.IOException: Server returned HTTP response code: 429 for URL: https://b.tile.openstreetmap.org/4/5/9.png
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at java.net.URL.openStream(URL.java:1045)
	at javax.imageio.ImageIO.read(ImageIO.java:1393)

**Comment by McPringle** [comment]
Hi @okievv, which version of GPX Animator are you using (menu "Help > About")? Can you please provide me the GPX file you are going to render and please save your settings and share the saved file (menu "File > Save As"). I'll try to reproduce your problem.

**Comment by okievv** [comment]
Hi @McPringle, here is the information you requested: release is 1.3.1, recently downloaded. PFA also the config file and a sample gpx file (I tried several ones with no luck).
[mapErrors.zip](https://github.com/zdila/gpx-animator/files/4005012/mapErrors.zip)

**Comment by McPringle** [comment]
@okievv, thank you very much for the data. A few days before Xmas I released v1.4. Please download the version from https://gpx-animator.app/ and check it out. I used you settings file and GPX file with v1.4 with success. The resulting video was successfully rendered with the OSM map. Pro tip: enter width and height manually for a better video resolution, e.g. 1920x1080 (FullHD).

**Comment by okievv** [comment]
Indeed, @McPringle, that hits the bulls eye: this works fine now. Thank you.
