### ISSUE TITLE
NoClassDefFoundError, ClassNotFoundException

### ISSUE THREAD

**Issue by answerquest** [zdila/gpx-animator#22]
Tried this on a fresh lubuntu 18.04 64-bit OS. Installed java by: `sudo apt-get install default-jdk`.

Got this error a minute or two after entering the launch command:
```
$ java -jar GpxAnimator-1.3.0.jar 
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at sk.freemap.gpxAnimator.Main$1.run(Main.java:35)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at com.simontuffs.onejar.JarClassLoader.findClass(JarClassLoader.java:713)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
	at com.simontuffs.onejar.JarClassLoader.loadClass(JarClassLoader.java:630)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 15 more
```
It could just be that my laptop's memory is low (but no memory error reported, and the `-Xmx1024m` produced same result), but please check if it's some libraries or something that need installing.

**Comment by zdila** [comment]
Thanks for the report. It is a compatibility issue. For now please run it with `--add-modules java.xml.bind` parameter.
