### ISSUE TITLE
Refactor font handling before release

### ISSUE THREAD

**Issue by McPringle** [zdila/gpx-animator#236]
There are three independent options:

1. font size (integer)
2. font name (string)
3. font style (string)

It would be better to use only one option which makes use of the Java `Font` object. The `Font` object contains all needed options (which font was selected, which style, and which size).

This provides a better overview of the UI and you can use one of the available Swing dialogs for font selection.

Attention: Font size selection has been available for some time, but font and style selection was introduced in GPX Animator version 1.6. So that no conversion of the saved data has to be built, this change should also be done with v1.6!

**Comment by poorlymac** [comment]
On the Mac the default font picked is ".AppleSystemUIFont" and when you click Render the following exception occurs:
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 194
        at app.gpx_animator.ui.GeneralSettingsPanel.buildConfiguration(GeneralSettingsPanel.java:1021)
        at app.gpx_animator.ui.MainFrame.createConfiguration(MainFrame.java:504)
        at app.gpx_animator.ui.MainFrame.lambda$new$15(MainFrame.java:392)

Which is .fontName(fontFamilyNames[(Integer) fontNameItem - 1])
