### ISSUE TITLE
Invalid video frame size when bounding box specified

### ISSUE THREAD

**Issue by pdroogers** [zdila/gpx-animator#238]
Excellent work!! 
Small error detected in Interface: MinLat and MaxLat works reverse (MinLat is now greater than MaxLat)
Potential improvements:
+ Using Margin will also move text, Better to leave text at same position.
+ Autofill Bounding Box based on the Track
+ For long tracks would be nice if the map also moves (would be major change I presume)

Thanks a lot, Peter

**Comment by McPringle** [comment]
Thank you very much for your bug report, @pdroogers. Can you please create a separate issue for each of your improvements?

**Comment by McPringle** [comment]
Hi @pdroogers, just an update to the potential improvements, you mentioned in addition to your issue: Thanks to @thomergil, a movable map, and separate margin definitions, will be part of v1.6.

**Comment by McPringle** [comment]
I can't see a problem here with min/max latitude/longitude. Do you have an example, @pdroogers?

**Comment by pdroogers** [comment]
Thanks for the update. Sorry for not being specific on the bug.

One would expect that MaxLat must be greater than MinLat. However, this gives an error. Making MaxLat smaller than MinLat it all works fine.

Here a file where you can see that MinLat is actually bigger than MaxLat
[202101.ga.xml.txt](https://github.com/zdila/gpx-animator/files/5771774/202101.ga.xml.txt)

Thx, PeterD

**Comment by McPringle** [comment]
Thanks for the configuration file. Do you mean the following error message?

```
java.lang.IllegalArgumentException: invalid video frame size [674 x -474]
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: invalid video frame size [674 x -474]
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
	at app.gpx_animator.ui.MainFrame$5.done(MainFrame.java:439)
	at java.desktop/javax.swing.SwingWorker$5.run(SwingWorker.java:750)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:847)
	at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:857)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:310)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:242)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.IllegalArgumentException: invalid video frame size [674 x -474]
	at com.xuggle.mediatool.MediaWriter.addVideoStream(MediaWriter.java:491)
	at com.xuggle.mediatool.MediaWriter.addVideoStream(MediaWriter.java:416)
	at app.gpx_animator.core.renderer.framewriter.VideoFrameWriter.<init>(VideoFrameWriter.java:33)
	at app.gpx_animator.Renderer.render(Renderer.java:169)
	at app.gpx_animator.ui.MainFrame$5.doInBackground(MainFrame.java:407)
	at app.gpx_animator.ui.MainFrame$5.doInBackground(MainFrame.java:404)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```
