### ISSUE TITLE
IllegalArgumentException: Dimensions are too large

### ISSUE THREAD

**Issue by McPringle** [zdila/gpx-animator#274]
```
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Dimensions (width=113542 height=180306) are too large
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
	at app.gpx_animator.ui.MainFrame$5.done(MainFrame.java:439)
	at java.desktop/javax.swing.SwingWorker$5.run(SwingWorker.java:750)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:847)
	at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:857)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:310)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:242)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.IllegalArgumentException: Dimensions (width=113542 height=180306) are too large
	at java.desktop/java.awt.image.SampleModel.<init>(SampleModel.java:130)
	at java.desktop/java.awt.image.ComponentSampleModel.<init>(ComponentSampleModel.java:140)
	at java.desktop/java.awt.image.PixelInterleavedSampleModel.<init>(PixelInterleavedSampleModel.java:87)
	at java.desktop/java.awt.image.Raster.createInterleavedRaster(Raster.java:642)
	at java.desktop/java.awt.image.Raster.createInterleavedRaster(Raster.java:278)
	at java.desktop/java.awt.image.BufferedImage.<init>(BufferedImage.java:376)
	at app.gpx_animator.Renderer.render(Renderer.java:167)
	at app.gpx_animator.ui.MainFrame$5.doInBackground(MainFrame.java:407)
	at app.gpx_animator.ui.MainFrame$5.doInBackground(MainFrame.java:404)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.IllegalArgumentException: Dimensions (width=113542 height=180306) are too large
```

This happens, when the size of the `BufferedImage` is too high. In the past, that was not a problem. But with the moving map feature, this can be a problem. Example: I want to create a Full HD moving map with a recorded GPX track. The size of the video will be 1'920 x 1'080, but depending on the zoom level of the map, the size of the underlying `BufferedImage` has to be much higher. Sometimes too high.

See: https://stackoverflow.com/questions/9089675/creating-huge-bufferedimage
Possible solution: https://github.com/leonbloy/pngj/

**Comment by thomergil** [comment]
@McPringle, thanks for looking into this. If this is due to moving map, I'm happy to try to address the bug. But I'm a little confused how this relates to the moving map feature. The viewport is always smaller than the actual map behind it, so I'm not sure how it relates. How do I reproduce this bug? Thank you.

**Comment by McPringle** [comment]
The viewport is like a window to the outside world, you just see a part of it. If you use the moving map feature, the background map itself is rendered at the beginning once with all tiles and much bigger than the viewport. There are four size values:

- width & height
- viewport width & height

The rule is very simple: width >= viewport width & height >= viewport height

Try this moving map with the example GPX file from the project:

`java -jar ./build/libs/gpx-animator-1.6.0-SNAPSHOT-all.jar --input .\src\test\resources\gpx\bikeride.gpx --output movie.mp4 --zoom 15 --viewport-width 640 --viewport-height 640`

This works. It will load 5'073 tiles and the background map will be 14'228 x 22'574 pixels in size.

`java -jar ./build/libs/gpx-animator-1.6.0-SNAPSHOT-all.jar --input .\src\test\resources\gpx\bikeride.gpx --output movie.mp4 --zoom 16 --viewport-width 640 --viewport-height 640`

This does not work. The size of the background map would be 28'416 x 45'108 pixels.

`java -jar ./build/libs/gpx-animator-1.6.0-SNAPSHOT-all.jar --input .\src\test\resources\gpx\bikeride.gpx --output movie.mp4 --zoom 18 --viewport-width 640 --viewport-height 640`

As expected (higher zoom level), it does not work. But very funny: Different exception...

Depending on the zoom level and/or the length of the GPX track (range of the map) the `BufferedImage` can't create the background map (I would guess it uses integer values to address the pixels internally which may overflow). For v1.6 I won't invest too much because I would like to release it soon. But catching the exceptions and wrapping them in a user-friendly error message should be no problem and an easy task. A deep analysis of how this problem can be solved could be done at a later time.

**Comment by thomergil** [comment]
This problem is not related to and not a consequence of the moving map feature. It is only related to the `--zoom` argument. I would expect the same crash to happen without the `--viewport-*` arguments. You are trying to render an enormous map.

However, I might believe that the existence of a moving map feature tricks users into believing they can render the map at higher zoom levels than they would have without the moving map feature. Users cannot know that, behind the scenes (or behind the viewport, maybe?), they are rendering an enormous map.

However, blaming this on the moving map feature seems a little misleading.

I agree, of course, that catching an exception and giving a user-friendly error is always a good idea. The error message should suggest they use a lower zoom value.

That all said, maybe it is possible to implement a moving map without pre-rendering the full map. It is only necessary to render the tiles that intersect with the current viewport. However, given this 30 seconds of thought, I suspect it adds *enormous* complexity. Would we dynamically glue map tiles into the viewport? We'd have to first pre-draw the track on it if that was enabled. Thinking about this makes my head spin. 🙂

**Comment by McPringle** [comment]
Sorry for the misunderstanding, I don't want to blame this on the moving map feature. As you wrote, the moving map feature will make the users choose a higher zoom level because they don't think of the enormous map "behind the scenes" and just see their Full HD resolution.

Before the moving map feature, this was never a problem. The map had as maximum the size of the movie dimensions. This changed now which made this new problem appear on the surface. We would have the same problem if someone tries to render a video for a 15k resolution TV, which might come in a few years. ;-)

But, as I said, it is not a problem we need to solve quickly. Just wrapping the exceptions in a good error message should be sufficient now.
