### ISSUE TITLE
BufferOverflowException when creating video files

### ISSUE THREAD

**Issue by McPringle** [zdila/gpx-animator#311]
When using a moving map, the following exception can occur:

````
java.nio.BufferOverflowException
java.util.concurrent.ExecutionException: java.nio.BufferOverflowException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
	at app.gpx_animator.ui.swing.MainFrame$5.done(MainFrame.java:457)
	at java.desktop/javax.swing.SwingWorker$5.run(SwingWorker.java:750)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:847)
	at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:857)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:310)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:242)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.nio.BufferOverflowException
	at java.base/java.nio.DirectByteBuffer.put(DirectByteBuffer.java:429)
	at java.base/java.nio.ByteBuffer.put(ByteBuffer.java:1100)
	at com.xuggle.xuggler.video.BgrConverter.toPicture(BgrConverter.java:132)
	at com.xuggle.mediatool.MediaWriter.convertToPicture(MediaWriter.java:970)
	at com.xuggle.mediatool.MediaWriter.encodeVideo(MediaWriter.java:805)
	at app.gpx_animator.core.renderer.framewriter.VideoFrameWriter.addFrame(VideoFrameWriter.java:39)
	at app.gpx_animator.core.renderer.Renderer.renderFrames(Renderer.java:251)
	at app.gpx_animator.core.renderer.Renderer.render(Renderer.java:187)
	at app.gpx_animator.ui.swing.MainFrame$5.doInBackground(MainFrame.java:425)
	at app.gpx_animator.ui.swing.MainFrame$5.doInBackground(MainFrame.java:422)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
````

I have example files from a user, which need to be kept private.

**Comment by McPringle** [comment]
Looks like this kind of exception occurs when the background map in the background behind the moving map is too big. The calculated zoom level, in this case, was 16. Reducing the zoom level manually to 14 solved the problem. I'll figure out where to catch this exception and show a descriptive error message with a possible solution to the user.

**Comment by McPringle** [comment]
Nope, that was not the case, I was wrong in my last statement. Take a look:
![image](https://user-images.githubusercontent.com/1254039/106386883-67787c80-63d7-11eb-92f9-7c6c103a462f.png)
![image](https://user-images.githubusercontent.com/1254039/106386940-b9210700-63d7-11eb-918a-d1a06a803936.png)

**Comment by McPringle** [comment]
Next guess: Here in Switzerland the moving map works with the same settings, but a different GPX file. The user, who reported this problem, had a GPX file from a different part of the world, south of the equator, where the longitude is negative:

![image](https://user-images.githubusercontent.com/1254039/106387221-0ce02000-63d9-11eb-878a-757ed9e54c14.png)

This problem could be related to the calculation of the viewport (which part of the map to show). If the dimensions are calculated wrong, the external libraries to render the video might get invalid values.

**Comment by McPringle** [comment]
Nope! Again, I was wrong with my guess. I had the idea to try it out to save the frames as images, which is supported by GPX Animator, and that worked:

![image](https://user-images.githubusercontent.com/1254039/106387539-888e9c80-63da-11eb-8177-b99bd591813c.png)

I got the expected output, frame by frame as an own image. The viewport of the moving map was correct. Everything looked like expected.

**Rendering the animation is correct. Saving each frame as a single image worked (`FileFrameWriter`), Saving all frames as a video crashes (`VideoFrameWriter`).**

But why? What is the difference? It is just an image that should be added to the video, which worked fine using a different GPX file. I have no idea, what's going on there...

**Comment by McPringle** [comment]
Next guess: For video encoding, GPX Animator uses the Xuggler library. That is no longer maintained and the use is deprecated. The last version 5.4, used by GPX Animator, is from 2012. We should check if we can move to a different library and if that solves this problem.

_Btw: This exception occurs not on every OS and OS version. Xuggler has only a very small amount of Java code and a huge amount of platform- and os-specific code. That explains why some users have this problem, others not._

**Comment by McPringle** [comment]
Yes! It looks like this issue was solved by replacing the end-of-life Xuggler library with #321. The Library replacement was done for v1.7, so I'll replan this issue for v1.7, too.
