### ISSUE TITLE
GPX timestamp parse error: DateTimeParseException: Text '2020-08-04T13:04:58+0000' could not be parsed, unparsed text found at index 22

### ISSUE THREAD

**Issue by tisp00n** [zdila/gpx-animator#327]
GPX file generated by Android PhotoMap application. Used as a tracker during holidays. 

java.lang.RuntimeException: internal error when parsing GPX file
java.util.concurrent.ExecutionException: java.lang.RuntimeException: internal error when parsing GPX file
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
	at app.gpx_animator.ui.MainFrame$5.done(MainFrame.java:439)
	at java.desktop/javax.swing.SwingWorker$5.run(SwingWorker.java:750)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:847)
	at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:857)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:310)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:242)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.RuntimeException: internal error when parsing GPX file
	at app.gpx_animator.GpxParser.parseGpx(GpxParser.java:50)
	at app.gpx_animator.Renderer.parseGPX(Renderer.java:410)
	at app.gpx_animator.Renderer.render(Renderer.java:120)
	at app.gpx_animator.ui.MainFrame$5.doInBackground(MainFrame.java:407)
	at app.gpx_animator.ui.MainFrame$5.doInBackground(MainFrame.java:404)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.time.format.DateTimeParseException: Text '2020-08-04T13:04:58+0000' could not be parsed, unparsed text found at index 22
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2054)
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1953)
	at java.base/java.time.ZonedDateTime.parse(ZonedDateTime.java:599)
	at java.base/java.time.ZonedDateTime.parse(ZonedDateTime.java:584)
	at app.gpx_animator.GpxContentHandler.endElement(GpxContentHandler.java:83)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:618)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1727)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2898)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:541)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:324)
	at java.xml/javax.xml.parsers.SAXParser.parse(SAXParser.java:197)
	at app.gpx_animator.GpxParser.parseGpx(GpxParser.java:46)
	... 10 more

[2020-08-30.zip](https://github.com/zdila/gpx-animator/files/5924891/2020-08-30.zip)

**Comment by McPringle** [comment]
The date and time format used in your file: `2020-08-04T13:04:58+0000`
The date and time format usually used by GPS devices: `2020-08-04T13:04:58Z`

In the past, we never had a GPX device producing relative timezones like "+0000". I'll check if it makes sense to extend the GPX parsing to support these type of format and how to handle it.

**Comment by McPringle** [comment]
I reviewed the specification: The timezone format "+0000" is not ISO8601 conform. ISO8601 specifies "+00:00:00", "+00:00", or "+00". All formats, which comply with ISO8601, are supported by GPX Animator. Result: Your Android PhotoMap application produces incorrect timestamp values. See: https://en.wikipedia.org/wiki/ISO_8601

**Comment by McPringle** [comment]
I'll close this issue because GPX Animator supports the complete ISO8601 specification. The error is on side of the Android PhotoMap application. They should fix the error. If you need help filing an issue there, I can offer to assist you.
