### ISSUE TITLE
Improvement: Error-handling if GPX contains an empty Track

### ISSUE THREAD

**Issue by rneppi** [zdila/gpx-animator#366]
If you use a GPX-file with a track but without track-points, there is no movie generated. But you get an error-message like this: 

```
java.util.NoSuchElementException
java.util.concurrent.ExecutionException: java.util.NoSuchElementException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
	at app.gpx_animator.ui.MainFrame$5.done(MainFrame.java:439)
	at java.desktop/javax.swing.SwingWorker$5.run(SwingWorker.java:750)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:847)
	at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:857)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:310)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:242)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.util.NoSuchElementException
	at java.base/java.util.TreeMap.key(TreeMap.java:1596)
	at java.base/java.util.TreeMap.firstKey(TreeMap.java:291)
	at app.gpx_animator.Renderer.mergeConnectedSpans(Renderer.java:502)
	at app.gpx_animator.Renderer.parseGPX(Renderer.java:435)
	at app.gpx_animator.Renderer.render(Renderer.java:123)
	at app.gpx_animator.ui.MainFrame$5.doInBackground(MainFrame.java:407)
	at app.gpx_animator.ui.MainFrame$5.doInBackground(MainFrame.java:404)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

Instead of this, can you please add an appearing Message like „There are no track-points in %GPX-File%“?
An example-GPX-File is attached.
[Leertrack-Test.gpx.zip](https://github.com/zdila/gpx-animator/files/6821276/Leertrack-Test.gpx.zip)

**Comment by McPringle** [comment]
There should not be an exception. An Exception should be an exception. 🤔 So I treat this as a bug. Thank you very much for reporting.
