### ISSUE TITLE
Exception when using newlines with a empty line in 'attribution'

### ISSUE THREAD

**Issue by stefanweisswange** [zdila/gpx-animator#396]
With v1.7.0, you can reproduce an exception by using two newlines with an empty line between them in the 'attribution' field.

Using this text works
> TEST
> %APPNAME_VERSION% - %MAP_ATTRIBUTION%

but inserting an empty line

> TEST
> 
> %APPNAME_VERSION% - %MAP_ATTRIBUTION%

shows this exception after a click on "Create Video".

`java.lang.IllegalArgumentException: Zero length string passed to TextLayout constructor.
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Zero length string passed to TextLayout constructor.
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
	at app.gpx_animator.ui.swing.MainFrame$5.done(MainFrame.java:484)
	at java.desktop/javax.swing.SwingWorker$5.run(SwingWorker.java:750)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:847)
	at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:857)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:310)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:242)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.IllegalArgumentException: Zero length string passed to TextLayout constructor.
	at java.desktop/java.awt.font.TextLayout.<init>(TextLayout.java:382)
	at app.gpx_animator.core.renderer.TextRenderer.renderText(TextRenderer.java:101)
	at app.gpx_animator.core.renderer.plugins.AttributionPlugin.renderFrame(AttributionPlugin.java:61)
	at app.gpx_animator.core.renderer.Renderer.renderFrames(Renderer.java:267)
	at app.gpx_animator.core.renderer.Renderer.render(Renderer.java:175)
	at app.gpx_animator.ui.swing.MainFrame$5.doInBackground(MainFrame.java:452)
	at app.gpx_animator.ui.swing.MainFrame$5.doInBackground(MainFrame.java:449)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
`

**Comment by McPringle** [comment]
Thank you very much for your report! This happens because GPX Animator is printing the attribution line by line on the animation background and can't calculate the width of the "empty" line. I'll check how to handle this properly.
