### ISSUE TITLE
Error rendering map if Attribution is empty

### ISSUE THREAD

**Issue by zdila** [zdila/gpx-animator#5]
Error rendering map if Attribution is empty.
```
Caused by: java.lang.IllegalArgumentException: Zero length string passed to TextLayout constructor.
	at java.awt.font.TextLayout.<init>(TextLayout.java:382)
	at sk.freemap.gpxAnimator.Renderer.printText(Renderer.java:477)
	...
```

**Comment by zdila** [comment]
fixed in 7b80cbd138ea046b75d4cc2f3e2a3aae6a9e3ecf
