### ISSUE TITLE
can't start

### ISSUE THREAD

**Issue by ThomasKujawa** [zdila/gpx-animator#59]
C:\Users\Thomas Kujawa\Downloads>java -jar GpxAnimator-1.3.1.jar
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Unknown Source)
        at java.io.ByteArrayOutputStream.toByteArray(Unknown Source)
        at com.simontuffs.onejar.JarClassLoader$ByteCode.<init>(JarClassLoader.java:153)
        at com.simontuffs.onejar.JarClassLoader.loadBytes(JarClassLoader.java:603)
        at com.simontuffs.onejar.JarClassLoader.loadByteCode(JarClassLoader.java:542)
        at com.simontuffs.onejar.JarClassLoader.load(JarClassLoader.java:452)
        at com.simontuffs.onejar.JarClassLoader.load(JarClassLoader.java:338)
        at com.simontuffs.onejar.Boot.run(Boot.java:322)
        at com.simontuffs.onejar.Boot.main(Boot.java:166)

WIN10 + Java 8 Update 201 (reinstalled twice, removed old versions before)

Can anyone help?

**Comment by McPringle** [comment]
When does this exception occur, on application start or while rendering?

**Comment by zdila** [comment]
Have you checked [FAQ](https://zdila.github.io/gpx-animator/)?

**Comment by ThomasKujawa** [comment]
@McPringle while starting

**Comment by ThomasKujawa** [comment]
@zdila Thanks. I've overlooked it.
