### ISSUE TITLE
Width (0) and height (0) must be > 0

### ISSUE THREAD

**Issue by svenove** [zdila/gpx-animator#79]
I get this error, no matter I enter as width and height.
Tested 1.3.1, 1.3.0 and 1.2.0.

Any ideas?

`D:\Downloads>java -jar GpxAnimator-1.3.1.jar
[  0%] computed zoom is -2147483648
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Width (0) and height (0) must be > 0
        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at javax.swing.SwingWorker.get(Unknown Source)
        at sk.freemap.gpxAnimator.ui.MainFrame$13$1.done(MainFrame.java:427)
        at javax.swing.SwingWorker$5.run(Unknown Source)
        at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
        at sun.swing.AccumulativeRunnable.run(Unknown Source)
        at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
        at javax.swing.Timer.fireActionPerformed(Unknown Source)
        at javax.swing.Timer$DoPostEvent.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Width (0) and height (0) must be > 0
        at java.awt.image.SampleModel.<init>(Unknown Source)
        at java.awt.image.ComponentSampleModel.<init>(Unknown Source)
        at java.awt.image.PixelInterleavedSampleModel.<init>(Unknown Source)
        at java.awt.image.Raster.createInterleavedRaster(Unknown Source)
        at java.awt.image.Raster.createInterleavedRaster(Unknown Source)
        at java.awt.image.BufferedImage.<init>(Unknown Source)
        at sk.freemap.gpxAnimator.Renderer.render(Renderer.java:192)
        at sk.freemap.gpxAnimator.ui.MainFrame$13$1.doInBackground(MainFrame.java:396)
        at sk.freemap.gpxAnimator.ui.MainFrame$13$1.doInBackground(MainFrame.java:393)
        at javax.swing.SwingWorker$1.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at javax.swing.SwingWorker.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)`

**Comment by McPringle** [comment]
Thank you very much for your report. Can you please provide an example GPX file and the saved settings (File > Save) you use? If you don't want it to make these files public in this issue, you can send them to my private email and I will keep them secret: marcus@fihlon.swiss

**Comment by rudem70** [comment]
Hello i've the same problem, 
udem@eos-vir:~/Scaricati$ java -jar Gpx14.jar
JarClassLoader: Warning: module-info.class in lib/jaxb-runtime-2.3.1.jar is hidden by lib/jaxb-api-2.3.1.jar (with different bytecode)
JarClassLoader: Warning: module-info.class in lib/txw2-2.3.1.jar is hidden by lib/jaxb-api-2.3.1.jar (with different bytecode)
JarClassLoader: Warning: com/sun/istack/XMLStreamReaderToContentHandler.class in lib/istack-commons-runtime-3.0.7.jar is hidden by lib/jaxb-core-2.3.0.1.jar (with different bytecode)
JarClassLoader: Warning: com/sun/istack/localization/NullLocalizable.class in lib/istack-commons-runtime-3.0.7.jar is hidden by lib/jaxb-core-2.3.0.1.jar (with different bytecode)
JarClassLoader: Warning: com/sun/istack/localization/LocalizableMessage.class in lib/istack-commons-runtime-3.0.7.jar is hidden by lib/jaxb-core-2.3.0.1.jar (with different bytecode)
JarClassLoader: Warning: com/sun/istack/localization/Localizer.class in lib/istack-commons-runtime-3.0.7.jar is hidden by lib/jaxb-core-2.3.0.1.jar (with different bytecode)
JarClassLoader: Warning: com/sun/istack/logging/Logger.class in lib/istack-commons-runtime-3.0.7.jar is hidden by lib/jaxb-core-2.3.0.1.jar (with different bytecode)
JarClassLoader: Warning: com/sun/istack/Pool$Impl.class in lib/istack-commons-runtime-3.0.7.jar is hidden by lib/jaxb-core-2.3.0.1.jar (with different bytecode)
JarClassLoader: Warning: module-info.class in lib/istack-commons-runtime-3.0.7.jar is hidden by lib/jaxb-api-2.3.1.jar (with different bytecode)
JarClassLoader: Warning: module-info.class in lib/stax-ex-1.8.jar is hidden by lib/jaxb-api-2.3.1.jar (with different bytecode)
JarClassLoader: Warning: module-info.class in lib/FastInfoset-1.2.15.jar is hidden by lib/jaxb-api-2.3.1.jar (with different bytecode)
JarClassLoader: Warning: javax/activation/ActivationDataFlavor.class in lib/activation-1.1.1.jar is hidden by lib/javax.activation-api-1.2.0.jar (with different bytecode)
JarClassLoader: Warning: javax/activation/CommandInfo.class in lib/activation-1.1.1.jar is hidden by lib/javax.activation-api-1.2.0.jar (with different bytecode)
JarClassLoader: Warning: javax/activation/CommandMap.class in lib/activation-1.1.1.jar is hidden by lib/javax.activation-api-1.2.0.jar (with different bytecode)
JarClassLoader: Warning: javax/activation/CommandObject.class in lib/activation-1.1.1.jar is hidden by lib/javax.activation-api-1.2.0.jar (with different bytecode)
JarClassLoader: Warning: javax/activation/DataContentHandler.class in lib/activation-1.1.1.jar is hidden by lib/javax.activation-api-1.2.0.jar (with different bytecode)
JarClassLoader: Warning: javax/activation/DataContentHandlerFactory.class in lib/activation-1.1.1.jar is hidden by lib/javax.activation-api-1.2.0.jar (with different bytecode)
JarClassLoader: Warning: javax/activation/DataHandler$1.class in lib/activation-1.1.1.jar is hidden by lib/javax.activation-api-1.2.0.jar (with different bytecode)
JarClassLoader: Warning: javax/activation/DataHandler.class in lib/activation-1.1.1.jar is hidden by lib/javax.activation-api-1.2.0.jar (with different bytecode)
JarClassLoader: Warning: javax/activation/DataHandlerDataSource.class in lib/activation-1.1.1.jar is hidden by lib/javax.activation-api-1.2.0.jar (with different bytecode)
JarClassLoader: Warning: javax/activation/DataSource.class in lib/activation-1.1.1.jar is hidden by lib/javax.activation-api-1.2.0.jar (with different bytecode)
JarClassLoader: Warning: javax/activation/DataSourceDataContentHandler.class in lib/activation-1.1.1.jar is hidden by lib/javax.activation-api-1.2.0.jar (with different bytecode)
JarClassLoader: Warning: javax/activation/FileDataSource.class in lib/activation-1.1.1.jar is hidden by lib/javax.activation-api-1.2.0.jar (with different bytecode)
JarClassLoader: Warning: javax/activation/FileTypeMap.class in lib/activation-1.1.1.jar is hidden by lib/javax.activation-api-1.2.0.jar (with different bytecode)
JarClassLoader: Warning: javax/activation/MailcapCommandMap.class in lib/activation-1.1.1.jar is hidden by lib/javax.activation-api-1.2.0.jar (with different bytecode)
JarClassLoader: Warning: javax/activation/MimeType.class in lib/activation-1.1.1.jar is hidden by lib/javax.activation-api-1.2.0.jar (with different bytecode)
JarClassLoader: Warning: javax/activation/MimeTypeParameterList.class in lib/activation-1.1.1.jar is hidden by lib/javax.activation-api-1.2.0.jar (with different bytecode)
JarClassLoader: Warning: javax/activation/MimeTypeParseException.class in lib/activation-1.1.1.jar is hidden by lib/javax.activation-api-1.2.0.jar (with different bytecode)
JarClassLoader: Warning: javax/activation/MimetypesFileTypeMap.class in lib/activation-1.1.1.jar is hidden by lib/javax.activation-api-1.2.0.jar (with different bytecode)
JarClassLoader: Warning: javax/activation/ObjectDataContentHandler.class in lib/activation-1.1.1.jar is hidden by lib/javax.activation-api-1.2.0.jar (with different bytecode)
JarClassLoader: Warning: javax/activation/SecuritySupport$1.class in lib/activation-1.1.1.jar is hidden by lib/javax.activation-api-1.2.0.jar (with different bytecode)
JarClassLoader: Warning: javax/activation/SecuritySupport$2.class in lib/activation-1.1.1.jar is hidden by lib/javax.activation-api-1.2.0.jar (with different bytecode)
JarClassLoader: Warning: javax/activation/SecuritySupport$3.class in lib/activation-1.1.1.jar is hidden by lib/javax.activation-api-1.2.0.jar (with different bytecode)
JarClassLoader: Warning: javax/activation/SecuritySupport$4.class in lib/activation-1.1.1.jar is hidden by lib/javax.activation-api-1.2.0.jar (with different bytecode)
JarClassLoader: Warning: javax/activation/SecuritySupport$5.class in lib/activation-1.1.1.jar is hidden by lib/javax.activation-api-1.2.0.jar (with different bytecode)
JarClassLoader: Warning: javax/activation/SecuritySupport.class in lib/activation-1.1.1.jar is hidden by lib/javax.activation-api-1.2.0.jar (with different bytecode)
JarClassLoader: Warning: javax/activation/URLDataSource.class in lib/activation-1.1.1.jar is hidden by lib/javax.activation-api-1.2.0.jar (with different bytecode)
JarClassLoader: Warning: javax/activation/UnsupportedDataTypeException.class in lib/activation-1.1.1.jar is hidden by lib/javax.activation-api-1.2.0.jar (with different bytecode)
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Width (0) and height (0) must be > 0
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
	at sk.freemap.gpxAnimator.ui.MainFrame$14$1.done(MainFrame.java:483)
	at java.desktop/javax.swing.SwingWorker$5.run(SwingWorker.java:750)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:847)
	at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:857)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.IllegalArgumentException: Width (0) and height (0) must be > 0
	at java.desktop/java.awt.image.SampleModel.<init>(SampleModel.java:126)
	at java.desktop/java.awt.image.ComponentSampleModel.<init>(ComponentSampleModel.java:140)
	at java.desktop/java.awt.image.PixelInterleavedSampleModel.<init>(PixelInterleavedSampleModel.java:87)
	at java.desktop/java.awt.image.Raster.createInterleavedRaster(Raster.java:642)
	at java.desktop/java.awt.image.Raster.createInterleavedRaster(Raster.java:278)
	at java.desktop/java.awt.image.BufferedImage.<init>(BufferedImage.java:376)
	at sk.freemap.gpxAnimator.Renderer.render(Renderer.java:190)
	at sk.freemap.gpxAnimator.ui.MainFrame$14$1.doInBackground(MainFrame.java:452)
	at sk.freemap.gpxAnimator.ui.MainFrame$14$1.doInBackground(MainFrame.java:449)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

[error.zip](https://github.com/zdila/gpx-animator/files/3515557/error.zip)

**Comment by NBOnGithub** [comment]
I get the same issue. Tried Mac and Windows Java 8 and 13. Tried GUI and command line. Using various width and height as well as zoom. Was using a sample GPX file for St Louis Zoo - http://www.geovative.com/GeoTours/downloadTourGPX.asp?6174Vq=GEIF

**Comment by McPringle** [comment]
@rudem70: Thank you very much for your data. The file "Kurviger.gpx" does not contain a recorded GPX track, just two points: A starting point and a finishing point. GPX Animator is not a navigation system and can't calculate a route. It can just take a recorded route and create a video of it. Maybe that was a misundestanding?

**Comment by McPringle** [comment]
@NBOnGithub: I tried to download the file but got an *HTTP Error 503. The service is unavailable.*

**Comment by McPringle** [comment]
@svenove: I requested the sample file a few months ago. I can't reproduce the problem and would like to try it with your files. If you can't provide me the files I'll close this issue soon.

**Comment by svenove** [comment]
@McPringle sorry, I found a different software that suited my needs and forgot all about this issue. I don’t have the GPX-file anymore, sorry.

**Comment by McPringle** [comment]
@svenove No Problem! I released a new version a few days ago and I would be happy if you give GPX Animator a second chance. Happy new year!

**Comment by phgiraud** [comment]
Hi,
Got the same issue. It occurs when the GPX file is made of <rte> and <rtept> elements only. Bug is not present with GPX files containing <trk> / <trkseg> / <trkpt> elements.
Hope it helps.

**Comment by zdila** [comment]
`rte` element has different meaning and should not be used for animation, just for route planning.

**Comment by phgiraud** [comment]
Got a GPX file from a Sunto export, where the track was actually recorded as a route, don't know if it is always the case (I do not own a Sunto GPS watch myself). I managed to convert it to regular track points. I can send you the GPX if you want.

Thanks anyway for this good software !

**Comment by zdila** [comment]
Thanks, I believe you, but I can do nothing for malformed (semantically incorrect) GPX files.

**Comment by McPringle** [comment]
For everybody else with this problem: It occurs, when a GPX file does contain a route instead of a track. Routes are simply a sequence of waypoints for navigation. Tracks are the actually recorded path. GPX Animator needs a track. See #178
